<?php

namespace isea\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function lastArticles(){
        return $this->_em
                ->createQueryBuilder()
                ->select('a')
                ->from('iseaAppBundle:Article', 'a')
                ->orderBy('a.date', 'desc')
                ->setMaxResults(3)
                ->getQuery()
                ->getResult();
    }
    public function articleBefore($id){
        return $this->_em
                ->createQueryBuilder()
                ->select('a')
                ->from('iseaAppBundle:Article', 'a')
                ->where('a.id < :id')
                ->setParameter('id', $id)
                ->orderBy('a.id')
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
    }
    public function articleAfter($id){
        return $this->_em
                ->createQueryBuilder()
                ->select('a')
                ->from('iseaAppBundle:Article', 'a')
                ->where('a.id > :id')
                ->setParameter('id', $id)
                ->orderBy('a.id')
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
    }
}
