<?php

namespace isea\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FideliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FideliteRepository extends EntityRepository
{
}
