isea\AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: isea\AppBundle\Entity\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        resume:
            type: text
        contenu:
            type: text
        date:
            type: datetime
    manyToOne:
        user:
            targetEntity: User
            inversedBy: articleUser
            joinColumn:
                name: idUser
                referencedColumnName: id
    lifecycleCallbacks: {  }